spring:
  application:
    name: client-servive

server:
  servlet:
    context-path: /
  port: 7003
  
eureka:
  client: 
    serviceUrl:
      defaultZone: http://eureka1:8001/eureka/,http://eureka2:8002/eureka/