server:
  port: 8001
  
eureka:
  server: 
    enable-self-preservation: false #关闭自我保护机制
    eviction-interval-timer-in-ms: 4000 #设置清理间隔（单位：毫秒 默认是60*1000）
  instance: 
    hostname: eureka1
    lease-renewal-interval-in-seconds: 10 #客户端向注册中心发送心跳的时间间隔
    lease-expiration-duration-in-seconds: 120 #注册中心检测客户端2分钟内还没发生心跳，就剔除客户端
  client:
    registerWithEureka: false #不把自己作为一个客户端注册到自己身上
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka2:8002/eureka/

      
